from __future__ import annotations

BR_CPF = "BR_CPF"
BR_RG = "BR_RG"
BR_CNS = "BR_CNS"
BR_CRM = "BR_CRM"
BR_CNPJ = "BR_CNPJ"
BR_CEP = "BR_CEP"
BR_PHONE = "BR_PHONE"
BR_EMAIL = "BR_EMAIL"
BR_ADDRESS = "BR_ADDRESS"
BR_HEALTH_INSURANCE = "BR_HEALTH_INSURANCE"
BR_CLINICAL_RECORD_ID = "BR_CLINICAL_RECORD_ID"
BR_VISIT_ID = "BR_VISIT_ID"
BR_EXAM_ID = "BR_EXAM_ID"
BR_AUTHORIZATION_ID = "BR_AUTHORIZATION_ID"
BR_DATE = "BR_DATE"
BR_AGE = "BR_AGE"
BR_PATIENT_NAME = "BR_PATIENT_NAME"
BR_FAMILY_MEMBER_NAME = "BR_FAMILY_MEMBER_NAME"
BR_HEALTHCARE_PROFESSIONAL_NAME = "BR_HEALTHCARE_PROFESSIONAL_NAME"
BR_INSTITUTION = "BR_INSTITUTION"
BR_WORKPLACE = "BR_WORKPLACE"
BR_SCHOOL = "BR_SCHOOL"
BR_CONTEXTUAL_IDENTIFIER = "BR_CONTEXTUAL_IDENTIFIER"

BR_ENTITY_TYPES: tuple[str, ...] = (
    BR_CPF,
    BR_RG,
    BR_CNS,
    BR_CRM,
    BR_CNPJ,
    BR_CEP,
    BR_PHONE,
    BR_EMAIL,
    BR_ADDRESS,
    BR_HEALTH_INSURANCE,
    BR_CLINICAL_RECORD_ID,
    BR_VISIT_ID,
    BR_EXAM_ID,
    BR_AUTHORIZATION_ID,
    BR_DATE,
    BR_AGE,
    BR_PATIENT_NAME,
    BR_FAMILY_MEMBER_NAME,
    BR_HEALTHCARE_PROFESSIONAL_NAME,
    BR_INSTITUTION,
    BR_WORKPLACE,
    BR_SCHOOL,
    BR_CONTEXTUAL_IDENTIFIER,
)

ENTITY_TO_PLACEHOLDER_PREFIX: dict[str, str] = {
    BR_CPF: "CPF",
    BR_RG: "RG",
    BR_CNS: "CNS",
    BR_CRM: "CRM",
    BR_CNPJ: "CNPJ",
    BR_CEP: "CEP",
    BR_PHONE: "TELEFONE",
    BR_EMAIL: "EMAIL",
    BR_ADDRESS: "ENDERECO",
    BR_HEALTH_INSURANCE: "CONVENIO",
    BR_CLINICAL_RECORD_ID: "PRONTUARIO",
    BR_VISIT_ID: "ATENDIMENTO",
    BR_EXAM_ID: "EXAME",
    BR_AUTHORIZATION_ID: "AUTORIZACAO",
    BR_DATE: "DATA",
    BR_AGE: "IDADE",
    BR_PATIENT_NAME: "PACIENTE",
    BR_FAMILY_MEMBER_NAME: "FAMILIAR",
    BR_HEALTHCARE_PROFESSIONAL_NAME: "PROFISSIONAL",
    BR_INSTITUTION: "INSTITUICAO",
    BR_WORKPLACE: "LOCAL_TRABALHO",
    BR_SCHOOL: "ESCOLA",
    BR_CONTEXTUAL_IDENTIFIER: "IDENTIFICADOR_CONTEXTUAL",
}

ENTITY_SPECIFICITY_ORDER: tuple[str, ...] = (
    BR_CPF,
    BR_CNS,
    BR_CRM,
    BR_CNPJ,
    BR_RG,
    BR_HEALTH_INSURANCE,
    BR_CLINICAL_RECORD_ID,
    BR_AUTHORIZATION_ID,
    BR_EXAM_ID,
    BR_VISIT_ID,
    BR_CEP,
    BR_PHONE,
    BR_EMAIL,
    BR_ADDRESS,
    BR_HEALTHCARE_PROFESSIONAL_NAME,
    BR_PATIENT_NAME,
    BR_FAMILY_MEMBER_NAME,
    BR_INSTITUTION,
    BR_WORKPLACE,
    BR_SCHOOL,
    BR_DATE,
    BR_AGE,
    BR_CONTEXTUAL_IDENTIFIER,
)

ENTITY_SPECIFICITY: dict[str, int] = {
    entity_type: len(ENTITY_SPECIFICITY_ORDER) - index
    for index, entity_type in enumerate(ENTITY_SPECIFICITY_ORDER)
}
