#!/usr/bin/env bash
set -euo pipefail

REPO_URL="${PHI_REPO_URL:-https://github.com/augustocaruso/phi-br-firewall.git}"
REPO_REF="${PHI_REF:-main}"
INSTALL_ROOT="${PHI_INSTALL_ROOT:-${XDG_DATA_HOME:-$HOME/.local/share}/phi-br-firewall}"
SOURCE_DIR="${PHI_SOURCE_DIR:-}"
REPO_DIR="${SOURCE_DIR:-$INSTALL_ROOT/repo}"
OPENCODE_CONFIG_DIR="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}"
OPENCODE_PLUGIN_DIR="$OPENCODE_CONFIG_DIR/plugins"
OPENCODE_WRAPPER="$OPENCODE_PLUGIN_DIR/phi-br-firewall.ts"
INSTALL_NLP="${PHI_INSTALL_NLP:-1}"
SPACY_PT_MODEL_PACKAGE="${PHI_SPACY_PT_MODEL_PACKAGE:-https://github.com/explosion/spacy-models/releases/download/pt_core_news_md-3.8.0/pt_core_news_md-3.8.0-py3-none-any.whl}"

log() {
  printf 'phi install: %s\n' "$*"
}

die() {
  printf 'phi install: error: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

install_uv_if_missing() {
  if command -v uv >/dev/null 2>&1; then
    return
  fi

  log "uv not found; installing uv with the official Astral installer"
  if command -v curl >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- https://astral.sh/uv/install.sh | sh
  else
    die "install uv first: https://docs.astral.sh/uv/getting-started/installation/"
  fi

  export PATH="$HOME/.local/bin:$PATH"
  command -v uv >/dev/null 2>&1 || die "uv was installed but is not on PATH"
}

checkout_repo() {
  if [ -n "$SOURCE_DIR" ]; then
    [ -f "$REPO_DIR/pyproject.toml" ] || die "PHI_SOURCE_DIR does not look like the repo root: $REPO_DIR"
    log "using local source: $REPO_DIR"
    return
  fi

  require_command git
  mkdir -p "$INSTALL_ROOT"

  if [ -d "$REPO_DIR/.git" ]; then
    log "updating $REPO_DIR"
    git -C "$REPO_DIR" fetch --depth 1 origin "$REPO_REF"
    git -C "$REPO_DIR" checkout --detach --force FETCH_HEAD
    return
  fi

  if [ -e "$REPO_DIR" ]; then
    die "$REPO_DIR exists but is not a git checkout; move it away and retry"
  fi

  log "cloning $REPO_URL#$REPO_REF"
  if ! git clone --depth 1 --branch "$REPO_REF" "$REPO_URL" "$REPO_DIR"; then
    rm -rf "$REPO_DIR"
    git clone --depth 1 "$REPO_URL" "$REPO_DIR"
    git -C "$REPO_DIR" fetch --depth 1 origin "$REPO_REF"
    git -C "$REPO_DIR" checkout --detach --force FETCH_HEAD
  fi
}

install_cli() {
  if [ "$INSTALL_NLP" = "0" ]; then
    log "installing phi CLI with uv"
    uv tool install --force "$REPO_DIR"
    return
  fi

  log "installing phi CLI with uv and spaCy"
  uv tool install --force "${REPO_DIR}[nlp]"
  install_spacy_model
}

phi_tool_python() {
  local tool_dir
  tool_dir="$(uv tool dir)/phi-br-presidio-firewall"

  if [ -x "$tool_dir/bin/python" ]; then
    printf '%s\n' "$tool_dir/bin/python"
    return
  fi
  if [ -x "$tool_dir/Scripts/python.exe" ]; then
    printf '%s\n' "$tool_dir/Scripts/python.exe"
    return
  fi

  return 1
}

install_spacy_model() {
  local python_bin
  python_bin="$(phi_tool_python)" || die "phi tool Python was not found after install"

  log "installing pt_core_news_md into the phi tool environment"
  case "$SPACY_PT_MODEL_PACKAGE" in
    http://*|https://*)
      local temp_dir wheel_path
      temp_dir="$(mktemp -d)"
      wheel_path="$temp_dir/pt_core_news_md.whl"
      if command -v curl >/dev/null 2>&1; then
        if ! curl --retry 3 -fL "$SPACY_PT_MODEL_PACKAGE" -o "$wheel_path"; then
          rm -rf "$temp_dir"
          die "failed to download the spaCy Portuguese model"
        fi
      elif command -v wget >/dev/null 2>&1; then
        if ! wget -O "$wheel_path" "$SPACY_PT_MODEL_PACKAGE"; then
          rm -rf "$temp_dir"
          die "failed to download the spaCy Portuguese model"
        fi
      else
        rm -rf "$temp_dir"
        die "install curl or wget to download the spaCy Portuguese model"
      fi
      if ! uv pip install --python "$python_bin" "$wheel_path"; then
        rm -rf "$temp_dir"
        die "failed to install the spaCy Portuguese model"
      fi
      rm -rf "$temp_dir"
      ;;
    *)
      uv pip install --python "$python_bin" "$SPACY_PT_MODEL_PACKAGE"
      ;;
  esac
}

phi_bin() {
  if command -v phi >/dev/null 2>&1; then
    command -v phi
    return
  fi

  for candidate in "$HOME/.local/bin/phi" "/opt/homebrew/bin/phi" "/usr/local/bin/phi"; do
    if [ -x "$candidate" ]; then
      printf '%s\n' "$candidate"
      return
    fi
  done

  return 1
}

install_opencode_wrapper() {
  local plugin_path="$REPO_DIR/packages/phi_br_firewall_opencode/src/plugin.ts"
  [ -f "$plugin_path" ] || die "OpenCode plugin entrypoint not found: $plugin_path"

  case "$plugin_path" in
    *" "*) die "install path contains spaces; set PHI_INSTALL_ROOT to a path without spaces and retry" ;;
  esac

  mkdir -p "$OPENCODE_PLUGIN_DIR"

  if [ -f "$OPENCODE_WRAPPER" ] && ! grep -q "Generated by phi-br-firewall installer" "$OPENCODE_WRAPPER"; then
    die "$OPENCODE_WRAPPER already exists and was not generated by this installer"
  fi

  cat >"$OPENCODE_WRAPPER" <<EOF
// Generated by phi-br-firewall installer. Do not edit.
// Source: $REPO_URL#$REPO_REF
export { server } from "file://$plugin_path"
EOF

  log "installed OpenCode plugin wrapper at $OPENCODE_WRAPPER"
}

run_check() {
  local binary
  binary="$(phi_bin)" || die "phi executable was not found after install"

  log "running phi check"
  if [ "$INSTALL_NLP" = "0" ]; then
    "$binary" check >/dev/null
  else
    PHI_NLP=1 "$binary" check >/dev/null
  fi
}

main() {
  cat <<'EOF'
phi-br-firewall beta installer

Important: Phi reduces PHI/PII leakage risk, but it is not perfect and is not
a guarantee of de-identification. Review redacted text before sending it to any
external model or service.

EOF

  install_uv_if_missing
  checkout_repo
  install_cli
  install_opencode_wrapper
  run_check

  cat <<EOF

Installed.

CLI:
  $(phi_bin)

OpenCode plugin:
  $OPENCODE_WRAPPER

Next steps:
  1. Restart OpenCode.
  2. Use: /phi <texto livre com prontuario>
  3. Run: phi check

Clipboard commands:
  phi redact
  phi restore
  phi purge --all
EOF
}

main "$@"
