#!/usr/bin/env bash
set -euo pipefail

INSTALL_ROOT="${PHI_INSTALL_ROOT:-${XDG_DATA_HOME:-$HOME/.local/share}/phi-br-firewall}"
OPENCODE_CONFIG_DIR="${OPENCODE_CONFIG_DIR:-$HOME/.config/opencode}"
OPENCODE_WRAPPER="$OPENCODE_CONFIG_DIR/plugins/phi-br-firewall.ts"

log() {
  printf 'phi uninstall: %s\n' "$*"
}

if [ "${PHI_PURGE_CURRENT_DIR:-0}" = "1" ] && command -v phi >/dev/null 2>&1; then
  log "purging sessions for the current directory"
  phi purge --all || true
fi

if [ -f "$OPENCODE_WRAPPER" ]; then
  if grep -q "Generated by phi-br-firewall installer" "$OPENCODE_WRAPPER"; then
    rm -f "$OPENCODE_WRAPPER"
    log "removed OpenCode wrapper: $OPENCODE_WRAPPER"
  else
    log "left non-generated OpenCode wrapper untouched: $OPENCODE_WRAPPER"
  fi
fi

if command -v uv >/dev/null 2>&1; then
  uv tool uninstall phi-br-presidio-firewall >/dev/null 2>&1 || true
  log "uninstalled uv tool: phi-br-presidio-firewall"
else
  log "uv not found; skipped uv tool uninstall"
fi

if [ "${PHI_REMOVE_INSTALL_ROOT:-0}" = "1" ]; then
  case "$INSTALL_ROOT" in
    "$HOME/.local/share/phi-br-firewall"|"$HOME"/.local/share/phi-br-firewall)
      rm -rf "$INSTALL_ROOT"
      log "removed install root: $INSTALL_ROOT"
      ;;
    *)
      log "refusing to remove custom install root automatically: $INSTALL_ROOT"
      ;;
  esac
else
  log "left install checkout in place: $INSTALL_ROOT"
fi

cat <<'EOF'

Uninstalled.

Clinical mappings are project-local runtime data and are not deleted by this
script unless you purged them before uninstalling. If `phi` is still available,
run `phi purge --all` from relevant project folders to remove active sessions.
EOF
